// 生成物: desktop/tools/gen_core_tables.mjs (Android 版の hmos_tables.json から)。手で直さない
#pragma once

namespace shunti {

struct RomajiPair { const char16_t* key; const char16_t* kana; };
// ローマ字 → かな (HarmonyOS 版 ROMAJI_TABLE と同じ)
constexpr RomajiPair ROMAJI_TABLE[] = {
    {u"a", u"あ"},
    {u"i", u"い"},
    {u"u", u"う"},
    {u"e", u"え"},
    {u"o", u"お"},
    {u"-", u"ー"},
    {u"ka", u"か"},
    {u"ki", u"き"},
    {u"ku", u"く"},
    {u"ke", u"け"},
    {u"ko", u"こ"},
    {u"kya", u"きゃ"},
    {u"kyi", u"きぃ"},
    {u"kyu", u"きゅ"},
    {u"kye", u"きぇ"},
    {u"kyo", u"きょ"},
    {u"sa", u"さ"},
    {u"si", u"し"},
    {u"su", u"す"},
    {u"se", u"せ"},
    {u"so", u"そ"},
    {u"shi", u"し"},
    {u"sha", u"しゃ"},
    {u"shu", u"しゅ"},
    {u"she", u"しぇ"},
    {u"sho", u"しょ"},
    {u"sya", u"しゃ"},
    {u"syi", u"しぃ"},
    {u"syu", u"しゅ"},
    {u"sye", u"しぇ"},
    {u"syo", u"しょ"},
    {u"ta", u"た"},
    {u"ti", u"ち"},
    {u"tu", u"つ"},
    {u"te", u"て"},
    {u"to", u"と"},
    {u"chi", u"ち"},
    {u"cha", u"ちゃ"},
    {u"chu", u"ちゅ"},
    {u"che", u"ちぇ"},
    {u"cho", u"ちょ"},
    {u"tsu", u"つ"},
    {u"tya", u"ちゃ"},
    {u"tyi", u"ちぃ"},
    {u"tyu", u"ちゅ"},
    {u"tye", u"ちぇ"},
    {u"tyo", u"ちょ"},
    {u"thi", u"てぃ"},
    {u"tha", u"てゃ"},
    {u"thu", u"てゅ"},
    {u"the", u"てぇ"},
    {u"tho", u"てょ"},
    {u"twu", u"とぅ"},
    {u"na", u"な"},
    {u"ni", u"に"},
    {u"nu", u"ぬ"},
    {u"ne", u"ね"},
    {u"no", u"の"},
    {u"nya", u"にゃ"},
    {u"nyi", u"にぃ"},
    {u"nyu", u"にゅ"},
    {u"nye", u"にぇ"},
    {u"nyo", u"にょ"},
    {u"nn", u"ん"},
    {u"ha", u"は"},
    {u"hi", u"ひ"},
    {u"hu", u"ふ"},
    {u"he", u"へ"},
    {u"ho", u"ほ"},
    {u"fu", u"ふ"},
    {u"fa", u"ふぁ"},
    {u"fi", u"ふぃ"},
    {u"fe", u"ふぇ"},
    {u"fo", u"ふぉ"},
    {u"hya", u"ひゃ"},
    {u"hyi", u"ひぃ"},
    {u"hyu", u"ひゅ"},
    {u"hye", u"ひぇ"},
    {u"hyo", u"ひょ"},
    {u"ma", u"ま"},
    {u"mi", u"み"},
    {u"mu", u"む"},
    {u"me", u"め"},
    {u"mo", u"も"},
    {u"mya", u"みゃ"},
    {u"myi", u"みぃ"},
    {u"myu", u"みゅ"},
    {u"mye", u"みぇ"},
    {u"myo", u"みょ"},
    {u"ya", u"や"},
    {u"yi", u"い"},
    {u"yu", u"ゆ"},
    {u"ye", u"いぇ"},
    {u"yo", u"よ"},
    {u"ra", u"ら"},
    {u"ri", u"り"},
    {u"ru", u"る"},
    {u"re", u"れ"},
    {u"ro", u"ろ"},
    {u"rya", u"りゃ"},
    {u"ryi", u"りぃ"},
    {u"ryu", u"りゅ"},
    {u"rye", u"りぇ"},
    {u"ryo", u"りょ"},
    {u"wa", u"わ"},
    {u"wi", u"うぃ"},
    {u"we", u"うぇ"},
    {u"wo", u"を"},
    {u"ga", u"が"},
    {u"gi", u"ぎ"},
    {u"gu", u"ぐ"},
    {u"ge", u"げ"},
    {u"go", u"ご"},
    {u"gya", u"ぎゃ"},
    {u"gyi", u"ぎぃ"},
    {u"gyu", u"ぎゅ"},
    {u"gye", u"ぎぇ"},
    {u"gyo", u"ぎょ"},
    {u"za", u"ざ"},
    {u"zi", u"じ"},
    {u"zu", u"ず"},
    {u"ze", u"ぜ"},
    {u"zo", u"ぞ"},
    {u"ji", u"じ"},
    {u"ja", u"じゃ"},
    {u"ju", u"じゅ"},
    {u"je", u"じぇ"},
    {u"jo", u"じょ"},
    {u"jya", u"じゃ"},
    {u"jyi", u"じぃ"},
    {u"jyu", u"じゅ"},
    {u"jye", u"じぇ"},
    {u"jyo", u"じょ"},
    {u"zya", u"じゃ"},
    {u"zyi", u"じぃ"},
    {u"zyu", u"じゅ"},
    {u"zye", u"じぇ"},
    {u"zyo", u"じょ"},
    {u"da", u"だ"},
    {u"di", u"ぢ"},
    {u"du", u"づ"},
    {u"de", u"で"},
    {u"do", u"ど"},
    {u"dya", u"ぢゃ"},
    {u"dyi", u"ぢぃ"},
    {u"dyu", u"ぢゅ"},
    {u"dye", u"ぢぇ"},
    {u"dyo", u"ぢょ"},
    {u"dhi", u"でぃ"},
    {u"dha", u"でゃ"},
    {u"dhu", u"でゅ"},
    {u"dhe", u"でぇ"},
    {u"dho", u"でょ"},
    {u"dwu", u"どぅ"},
    {u"ba", u"ば"},
    {u"bi", u"び"},
    {u"bu", u"ぶ"},
    {u"be", u"べ"},
    {u"bo", u"ぼ"},
    {u"bya", u"びゃ"},
    {u"byi", u"びぃ"},
    {u"byu", u"びゅ"},
    {u"bye", u"びぇ"},
    {u"byo", u"びょ"},
    {u"pa", u"ぱ"},
    {u"pi", u"ぴ"},
    {u"pu", u"ぷ"},
    {u"pe", u"ぺ"},
    {u"po", u"ぽ"},
    {u"pya", u"ぴゃ"},
    {u"pyi", u"ぴぃ"},
    {u"pyu", u"ぴゅ"},
    {u"pye", u"ぴぇ"},
    {u"pyo", u"ぴょ"},
    {u"va", u"ゔぁ"},
    {u"vi", u"ゔぃ"},
    {u"vu", u"ゔ"},
    {u"ve", u"ゔぇ"},
    {u"vo", u"ゔぉ"},
    {u"xa", u"ぁ"},
    {u"xi", u"ぃ"},
    {u"xu", u"ぅ"},
    {u"xe", u"ぇ"},
    {u"xo", u"ぉ"},
    {u"xya", u"ゃ"},
    {u"xyu", u"ゅ"},
    {u"xyo", u"ょ"},
    {u"xtu", u"っ"},
    {u"xtsu", u"っ"},
    {u"xwa", u"ゎ"},
    {u"la", u"ぁ"},
    {u"li", u"ぃ"},
    {u"lu", u"ぅ"},
    {u"le", u"ぇ"},
    {u"lo", u"ぉ"},
    {u"lya", u"ゃ"},
    {u"lyu", u"ゅ"},
    {u"lyo", u"ょ"},
    {u"ltu", u"っ"},
    {u"ltsu", u"っ"},
};

struct SlurRule { const char16_t* word; const char16_t* not_after[6]; };
// 候補に含まれていたら弾く語 (not_after = その語の直後に来ていれば弾かない語。nullptr で終わる)
constexpr SlurRule SLURS[] = {
    {u"ガイジ", {nullptr}},
    {u"害児", {nullptr}},
    {u"池沼", {nullptr}},
    {u"キチガイ", {nullptr}},
    {u"きちがい", {nullptr}},
    {u"気違い", {nullptr}},
    {u"気狂い", {nullptr}},
    {u"基地外", {nullptr}},
    {u"キチゲェ", {nullptr}},
    {u"チョン", {u"マゲ", u"ボ", u"チョン", u"ガー", nullptr}},
    {u"チャンコロ", {nullptr}},
    {u"支那人", {nullptr}},
    {u"シナ人", {nullptr}},
    {u"土人", {nullptr}},
    {u"ニガー", {nullptr}},
    {u"ニガ―", {nullptr}},
    {u"黒んぼ", {nullptr}},
    {u"クロンボ", {nullptr}},
    {u"エタ非人", {nullptr}},
    {u"めくら", {nullptr}},
    {u"メクラ", {nullptr}},
    {u"つんぼ", {nullptr}},
    {u"ツンボ", {nullptr}},
    {u"知恵遅れ", {nullptr}},
    {u"片輪", {nullptr}},
    {u"かたわ", {nullptr}},
    {u"三国人", {nullptr}},
    {u"ジャップ", {nullptr}},
    {u"鮮人", {nullptr}},
    {u"ホモガキ", {nullptr}},
};

struct Phrase2 { const char16_t* reading; const char16_t* text; int min_prefix; };
// 決まり文句の予測 (読みの頭を min_prefix 字以上打ったら、候補の先頭に出す)
constexpr Phrase2 PREDICTIVE_PHRASES[] = {
    {u"あけましておめでとうございます", u"あけましておめでとうございます", 4},
    {u"おめでとうございます", u"おめでとうございます", 6},
    {u"たんじょうびおめでとうございます", u"誕生日おめでとうございます", 8},
    {u"よろしくおねがいします", u"よろしくお願いします", 5},
    {u"よろしくおねがいいたします", u"よろしくお願いいたします", 5},
    {u"どうぞよろしくおねがいします", u"どうぞよろしくお願いします", 5},
    {u"こんごともよろしくおねがいします", u"今後ともよろしくお願いします", 6},
    {u"なにとぞよろしくおねがいもうしあげます", u"何卒よろしくお願い申し上げます", 5},
    {u"おつかれさまでした", u"お疲れ様でした", 6},
    {u"おつかれさまです", u"お疲れ様です", 6},
    {u"ありがとうございます", u"ありがとうございます", 6},
    {u"ありがとうございました", u"ありがとうございました", 6},
    {u"いつもありがとうございます", u"いつもありがとうございます", 5},
    {u"おせわになっております", u"お世話になっております", 5},
    {u"おせわになりました", u"お世話になりました", 5},
    {u"たいへんおせわになりました", u"大変お世話になりました", 6},
    {u"ごぶさたしております", u"ご無沙汰しております", 5},
    {u"しつれいします", u"失礼します", 5},
    {u"しつれいいたします", u"失礼いたします", 5},
    {u"かしこまりました", u"かしこまりました", 6},
    {u"しょうちいたしました", u"承知いたしました", 6},
    {u"おまたせしました", u"お待たせしました", 5},
    {u"おげんきですか", u"お元気ですか", 5},
    {u"おはようございます", u"おはようございます", 6},
    {u"たいへんもうしわけございません", u"大変申し訳ございません", 6},
    {u"おてすうをおかけしますが", u"お手数をおかけしますが", 5},
    {u"ごかくにんよろしくおねがいします", u"ご確認よろしくお願いします", 6},
    {u"よいおとしを", u"よいお年を", 4},
};

}  // namespace shunti
